on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Extract version from tag
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v*}" >> $GITHUB_ENV

      # Ensure version is set correct
      - name: Run versioning script
        run: ./.github/scripts/setVersion.sh "$RELEASE_VERSION"
        shell: bash

      # Zip up addon files
      - name: Archive Addon Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: release.zip
          exclusions: '*.git* *.github*'

      # Upload Release
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: "${{ secrets.GITHUB_TOKEN }}"

      # Commit changed files back to repo
      - name: Commit version file back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Version Bump"
